export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  'ROLE.LEARNER': ['PERM.LRN.ACCESS'],
  'ROLE.MANAGER': ['PERM.LRN.ACCESS', 'PERM.MGR.TEAM.VIEW', 'PERM.MGR.TEAM.NUDGE'],
  'ROLE.ADMIN_VIEWER': ['PERM.ADM.DASHBOARD.VIEW'],
  'ROLE.ADMIN_CONTENT': ['PERM.ADM.DASHBOARD.VIEW', 'PERM.ADM.JOURNEYS.MANAGE', 'PERM.ADM.CONTENT.MANAGE'],
  'ROLE.ADMIN_REVIEWER': ['PERM.ADM.DASHBOARD.VIEW', 'PERM.ADM.CLAIMS.REVIEW'],
  'ROLE.ADMIN_TENANT': [
    'PERM.ADM.DASHBOARD.VIEW',
    'PERM.ADM.USERS.MANAGE',
    'PERM.ADM.COHORTS.MANAGE',
    'PERM.ADM.JOURNEYS.MANAGE',
    'PERM.ADM.CONTENT.MANAGE',
    'PERM.ADM.CLAIMS.REVIEW',
    'PERM.ADM.REWARDS.MANAGE',
    'PERM.ADM.SETTINGS.MANAGE',
    'PERM.ADM.AUDIT.VIEW',
  ],
  'ROLE.SUPER_ADMIN': ['*'],
};

export const CLAIM_REVIEW_ROLES = new Set(['ROLE.ADMIN_TENANT', 'ROLE.ADMIN_CONTENT', 'ROLE.ADMIN_REVIEWER']);
